- name: Setup EC2 instance
  hosts: all
  become: true
  vars_files:
    - vault.yml
  tasks:

    - name: Update apt packages
      ansible.builtin.apt:
        update_cache: true

    - name: Install required system packages
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: true

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present
        filename: docker

    - name: Update apt cache after adding Docker repo
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install Docker
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose
        state: present

    - name: Ensure Docker is enabled and started
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true

    - name: Add ubuntu user to docker group
      ansible.builtin.user:
        name: ubuntu
        groups: docker
        append: true

    - name: Reboot the server to apply group changes
      ansible.builtin.reboot:
        msg: "Reboot initiated by Ansible after adding user to docker group"
        connect_timeout: 5
        reboot_timeout: 600
        pre_reboot_delay: 0
        post_reboot_delay: 30

    - name: Check Docker status with docker info
      ansible.builtin.command: docker info
      register: docker_info_output
      changed_when: false
      failed_when: docker_info_output.rc != 0

    - name: Copy docker-compose.yml with permissions
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        mode: '0644'

    - name: Copy .env with permissions
      ansible.builtin.copy:
        src: .env
        dest: /home/ubuntu/.env
        mode: '0644'
